from pynput.keyboard import Key, Controller
import time
import os

cmd = 'color 02'     
os.system(cmd)

cmd = 'mode 65,42'
os.system(cmd)

keyboard = Controller()

time.sleep(0.5)

print('   ')
time.sleep(0.1)
print('   =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=')
time.sleep(0.1)
print('   ')
time.sleep(0.1)
print('                 _        _                      ')   
time.sleep(0.1)
print('                | |      | |                        ')
time.sleep(0.1)
print('      __ _ _   _| |_ ___ | |_ _   _ _ __   ___ _ __ ')
time.sleep(0.1)
print('     / _` | | | | __/ _ \| __| | | | ._ \ / _ \ |__|')
time.sleep(0.1)
print('    | (_| | |_| | || (_) | |_| |_| | |_) |  __/ |   ')
time.sleep(0.1)
print('     \__,_|\__,_|\__\___/ \__|\__, | .__/ \___|_|  ') 
time.sleep(0.1)
print('                               __/ | |     __  ')        
time.sleep(0.1)
print('                              |___/|_|    / _|   ')                     
time.sleep(0.1)
print('                                          | |_ _ __ ___  ___ ') 
time.sleep(0.1)
print('                                          |  _| |__/ _ \/ _ \ ') 
time.sleep(0.1)
print('                                          | | | | |  __/  __/') 
time.sleep(0.1)
print('                                          |_| |_|  \___|\___|') 
time.sleep(0.1)
print('   ')
time.sleep(0.1)
print('   =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=')
time.sleep(0.1)
print('   ')
time.sleep(0.1)
text = input("   Text you want to be spammed: ")
time.sleep(0.1)
print('   ')
time.sleep(0.1)
delay = float(input("   Delay (seconds): "))
time.sleep(0.1)
print('   ')
time.sleep(0.1)
actions = int(input ("   Number of messages: "))
print('   ')
time.sleep(0.1)
print('   =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=')
time.sleep(2)
print('   ')
time.sleep(0.1)
print('   Initializing script . . .')
time.sleep(3)
print('   ')
time.sleep(0.1)
print('   Please switch to a tab, script will begin in 5 seconds')
print('   ')
print('   =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=')

time.sleep(5)

x = 0

while (x < actions):

    keyboard.type(text)
    keyboard.press(Key.enter)
    x = x + 1
    time.sleep(delay)

print('   ')
print('   Thanks for using AutotyperFree! You can close the tab now.')
print('   ')
print('   If you want to support the creator, follow these links:')
print('   ')
print('   Instagram: https://www.instagram.com/andrei.tho/')
print('   YouTube: https://www.youtube.com/stra1gh7/')
print('   TikTok: https://www.tiktok.com/@stra1gh7?lang=en/')
print('   ')
print('   =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=')
time.sleep(10000)
